packages:
  - "apps/*"
  - "packages/*"
  - "packages/runtime/*"
  - "plugins/*"
  - "examples"
allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true

supportedArchitectures:
  os:
    - current
    - darwin
    - win32
  cpu:
    - current
    - x64
    - arm64
