export const MISSION_CHAT_PAGE_SIZE = 200;
export const MISSION_WORK_CONVERSATION_PAGE_SIZE = 50;
export const MISSION_WORK_RECORD_PAGE_SIZE = 20;
export const MISSION_CHAT_STREAM_FLUSH_INTERVAL_MS = 50;
