import { readFile, stat } from "node:fs/promises";

import { strFromU8, strToU8, unzip, zip, type AsyncUnzipOptions } from "fflate";

import {
  PRAGMA_BUNDLE_DIRECT_READ_VERSIONS,
  PragmaBundleManifestSchema,
  type PragmaBundleManifest,
} from "../ast/pragma-bundle.schema.ts";
import { sha256, stableStringify } from "../compiler/compiler-hash.ts";

export const DEFAULT_PRAGMA_BUNDLE_LIMITS = {
  maxArchiveBytes: 512 * 1024 * 1024,
  maxUnpackedBytes: 1024 * 1024 * 1024,
  maxFiles: 20_000,
} as const;

export interface PragmaBundleLimits {
  readonly maxArchiveBytes?: number | undefined;
  readonly maxUnpackedBytes?: number | undefined;
  readonly maxFiles?: number | undefined;
}

interface ResolvedPragmaBundleLimits {
  readonly maxArchiveBytes: number;
  readonly maxUnpackedBytes: number;
  readonly maxFiles: number;
}

export type PragmaBundleBinarySource =
  | { readonly kind: "file"; readonly path: string }
  | { readonly kind: "bytes"; readonly bytes: Uint8Array };

export interface DecodedPragmaBundle {
  readonly manifest: PragmaBundleManifest;
  /** Includes bundle.json so callers can preserve or inspect the exact archive contents. */
  readonly files: ReadonlyMap<string, Uint8Array>;
  readonly archiveBytes: number;
}

export type PragmaBundleFormatErrorCode =
  | "archive.invalid"
  | "archive.limit_exceeded"
  | "archive.path_unsafe"
  | "archive.path_collision"
  | "manifest.missing"
  | "manifest.invalid"
  | "manifest.version_unsupported"
  | "manifest.file_index_mismatch"
  | "manifest.file_verification_failed"
  | "manifest.fingerprint_invalid";

export class PragmaBundleFormatError extends Error {
  constructor(
    readonly code: PragmaBundleFormatErrorCode,
    message: string,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = "PragmaBundleFormatError";
  }
}

export function createPragmaBundleFingerprint(
  manifest: Omit<PragmaBundleManifest, "bundleFingerprint"> | PragmaBundleManifest,
): string {
  return sha256(
    stableStringify({
      schemaVersion: manifest.schemaVersion,
      createdAt: manifest.createdAt,
      roots: manifest.roots,
      project: manifest.project,
      requirements: manifest.requirements,
      extensions: manifest.extensions,
      files: manifest.files,
    }),
  );
}

export async function encodePragmaBundle(input: {
  readonly manifest: Omit<PragmaBundleManifest, "bundleFingerprint" | "files">;
  readonly files: ReadonlyMap<string, Uint8Array>;
  readonly limits?: PragmaBundleLimits | undefined;
}): Promise<{ readonly bytes: Uint8Array; readonly manifest: PragmaBundleManifest }> {
  const limits = resolveBundleLimits(input.limits);
  if (input.files.has("bundle.json")) {
    throw new PragmaBundleFormatError(
      "manifest.file_index_mismatch",
      "bundle.json is generated by the codec and must not be supplied as a payload file.",
    );
  }
  const seen = new Set<string>();
  const files = [...input.files]
    .map(([rawPath, contents]) => {
      const path = normalizeArchivePath(rawPath, false);
      const collisionKey = portableCollisionKey(path);
      if (seen.has(collisionKey)) {
        throw new PragmaBundleFormatError(
          "archive.path_collision",
          `Duplicate or non-portable bundle path: ${rawPath}`,
        );
      }
      seen.add(collisionKey);
      return { path, contents: contents.slice() };
    })
    .toSorted((left, right) => left.path.localeCompare(right.path));
  if (files.length + 1 > limits.maxFiles) {
    throw new PragmaBundleFormatError(
      "archive.limit_exceeded",
      "The .pragma archive exceeds its configured file limit.",
    );
  }
  const fileIndex = files.map(({ path, contents }) => ({
    path,
    size: contents.byteLength,
    sha256: sha256(contents),
  }));
  const withoutFingerprint = { ...input.manifest, files: fileIndex };
  const manifest = PragmaBundleManifestSchema.parse({
    ...withoutFingerprint,
    bundleFingerprint: createPragmaBundleFingerprint(withoutFingerprint),
  });
  const archive = new Map(files.map(({ path, contents }) => [path, contents]));
  archive.set("bundle.json", strToU8(`${JSON.stringify(manifest, undefined, 2)}\n`));
  const unpackedBytes = [...archive.values()].reduce(
    (total, contents) => total + contents.byteLength,
    0,
  );
  if (unpackedBytes > limits.maxUnpackedBytes) {
    throw new PragmaBundleFormatError(
      "archive.limit_exceeded",
      "The unpacked .pragma archive exceeds its configured limits.",
    );
  }
  const bytes = await zipArchive(archive);
  assertArchiveByteLimit(bytes.byteLength, limits.maxArchiveBytes);
  return { bytes, manifest };
}

export async function decodePragmaBundle(
  source: PragmaBundleBinarySource,
  configuredLimits: PragmaBundleLimits = {},
): Promise<DecodedPragmaBundle> {
  const limits = resolveBundleLimits(configuredLimits);
  if (source.kind === "file") {
    assertArchiveByteLimit((await stat(source.path)).size, limits.maxArchiveBytes);
  } else {
    assertArchiveByteLimit(source.bytes.byteLength, limits.maxArchiveBytes);
  }
  const raw =
    source.kind === "file" ? new Uint8Array(await readFile(source.path)) : source.bytes.slice();

  const seenPaths = new Set<string>();
  let indexedFiles = 0;
  let indexedBytes = 0;
  const filter: NonNullable<AsyncUnzipOptions["filter"]> = (file) => {
    const path = normalizeArchivePath(file.name, true);
    const collisionKey = portableCollisionKey(path.replace(/\/$/, ""));
    if (seenPaths.has(collisionKey)) {
      throw new PragmaBundleFormatError(
        "archive.path_collision",
        `Duplicate or non-portable bundle path: ${file.name}`,
      );
    }
    seenPaths.add(collisionKey);
    indexedFiles += 1;
    indexedBytes += file.originalSize;
    if (indexedFiles > limits.maxFiles || indexedBytes > limits.maxUnpackedBytes) {
      throw new PragmaBundleFormatError(
        "archive.limit_exceeded",
        "The unpacked .pragma archive exceeds its configured limits.",
      );
    }
    return true;
  };
  let unpacked: Record<string, Uint8Array>;
  try {
    unpacked = await unzipArchive(raw, { filter });
  } catch (error) {
    if (error instanceof PragmaBundleFormatError) throw error;
    throw new PragmaBundleFormatError(
      "archive.invalid",
      "The selected .pragma file is not a readable ZIP archive.",
      { cause: error },
    );
  }

  const files = new Map<string, Uint8Array>();
  let unpackedBytes = 0;
  for (const [rawPath, contents] of Object.entries(unpacked)) {
    const path = normalizeArchivePath(rawPath, true);
    if (path.endsWith("/")) continue;
    unpackedBytes += contents.byteLength;
    if (files.size >= limits.maxFiles || unpackedBytes > limits.maxUnpackedBytes) {
      throw new PragmaBundleFormatError(
        "archive.limit_exceeded",
        "The unpacked .pragma archive exceeds its configured limits.",
      );
    }
    files.set(path, contents);
  }

  const manifestSource = files.get("bundle.json");
  if (manifestSource === undefined) {
    throw new PragmaBundleFormatError("manifest.missing", "The bundle is missing bundle.json.");
  }
  let manifestValue: unknown;
  try {
    manifestValue = JSON.parse(strFromU8(manifestSource)) as unknown;
  } catch (error) {
    throw new PragmaBundleFormatError("manifest.invalid", "bundle.json is not valid JSON.", {
      cause: error,
    });
  }
  const version =
    typeof manifestValue === "object" && manifestValue !== null
      ? (manifestValue as Record<string, unknown>)["schemaVersion"]
      : undefined;
  if (!(PRAGMA_BUNDLE_DIRECT_READ_VERSIONS as readonly unknown[]).includes(version)) {
    throw new PragmaBundleFormatError(
      "manifest.version_unsupported",
      `Unsupported .pragma bundle version: ${String(version)}.`,
    );
  }
  const parsed = PragmaBundleManifestSchema.safeParse(manifestValue);
  if (!parsed.success) {
    throw new PragmaBundleFormatError(
      "manifest.invalid",
      `Invalid bundle.json: ${parsed.error.issues.map((issue) => issue.message).join("; ")}`,
    );
  }
  const manifest = parsed.data;
  const expectedFiles = new Set(manifest.files.map((file) => file.path));
  const actualFiles = new Set([...files.keys()].filter((path) => path !== "bundle.json"));
  if (
    expectedFiles.size !== actualFiles.size ||
    [...expectedFiles].some((path) => !actualFiles.has(path))
  ) {
    throw new PragmaBundleFormatError(
      "manifest.file_index_mismatch",
      "The bundle file index does not match the archive.",
    );
  }
  for (const indexed of manifest.files) {
    const contents = files.get(indexed.path);
    if (
      contents === undefined ||
      contents.byteLength !== indexed.size ||
      sha256(contents) !== indexed.sha256
    ) {
      throw new PragmaBundleFormatError(
        "manifest.file_verification_failed",
        `Bundle file verification failed: ${indexed.path}`,
      );
    }
  }
  if (createPragmaBundleFingerprint(manifest) !== manifest.bundleFingerprint) {
    throw new PragmaBundleFormatError(
      "manifest.fingerprint_invalid",
      "The bundle manifest fingerprint is invalid.",
    );
  }
  for (const requirement of manifest.requirements) {
    if (requirement.payload === undefined) continue;
    verifyPayloadRoot(files, requirement.payload.root, requirement.payload.fingerprint);
  }
  for (const extension of manifest.extensions) {
    verifyPayloadRoot(files, extension.root, extension.fingerprint);
  }
  const declaredAssetRoots = manifest.requirements.flatMap((requirement) =>
    requirement.payload === undefined ? [] : [requirement.payload.root],
  );
  const declaredExtensionRoots = manifest.extensions.map((extension) => extension.root);
  for (const path of files.keys()) {
    if (
      path.startsWith("assets/") &&
      !declaredAssetRoots.some((root) => path.startsWith(`${root}/`))
    ) {
      throw new PragmaBundleFormatError(
        "manifest.file_index_mismatch",
        `Bundle asset is not declared by a requirement: ${path}`,
      );
    }
    if (
      path.startsWith("extensions/") &&
      !declaredExtensionRoots.some((root) => path.startsWith(`${root}/`))
    ) {
      throw new PragmaBundleFormatError(
        "manifest.file_index_mismatch",
        `Bundle extension file is not declared: ${path}`,
      );
    }
  }
  return { manifest, files, archiveBytes: raw.byteLength };
}

function resolveBundleLimits(configured: PragmaBundleLimits = {}): ResolvedPragmaBundleLimits {
  const limits = {
    maxArchiveBytes: configured.maxArchiveBytes ?? DEFAULT_PRAGMA_BUNDLE_LIMITS.maxArchiveBytes,
    maxUnpackedBytes: configured.maxUnpackedBytes ?? DEFAULT_PRAGMA_BUNDLE_LIMITS.maxUnpackedBytes,
    maxFiles: configured.maxFiles ?? DEFAULT_PRAGMA_BUNDLE_LIMITS.maxFiles,
  };
  for (const [name, value] of Object.entries(limits)) {
    if (!Number.isSafeInteger(value) || value <= 0) {
      throw new PragmaBundleFormatError(
        "archive.limit_exceeded",
        `The .pragma ${name} limit must be a positive safe integer.`,
      );
    }
  }
  return limits;
}

function assertArchiveByteLimit(size: number, maxArchiveBytes: number): void {
  if (size === 0 || size > maxArchiveBytes) {
    throw new PragmaBundleFormatError(
      "archive.limit_exceeded",
      `The .pragma archive must be between 1 byte and ${maxArchiveBytes} bytes.`,
    );
  }
}

function verifyPayloadRoot(
  files: ReadonlyMap<string, Uint8Array>,
  root: string,
  expectedFingerprint: string,
): void {
  const prefix = `${root}/`;
  const entries = [...files]
    .filter(([path]) => path.startsWith(prefix))
    .map(([path, contents]) => ({ path: path.slice(prefix.length), sha256: sha256(contents) }))
    .toSorted((left, right) => left.path.localeCompare(right.path));
  if (entries.length === 0 || sha256(stableStringify(entries)) !== expectedFingerprint) {
    throw new PragmaBundleFormatError(
      "manifest.file_verification_failed",
      `Bundle payload verification failed: ${root}`,
    );
  }
}

function normalizeArchivePath(path: string, allowDirectory: boolean): string {
  if (path.includes("\\") || path.includes("\0") || path.startsWith("/") || /^[a-z]:/i.test(path)) {
    throw new PragmaBundleFormatError("archive.path_unsafe", `Unsafe bundle path: ${path}`);
  }
  const isDirectory = allowDirectory && path.endsWith("/");
  const segments = path.split("/");
  if (isDirectory) segments.pop();
  if (
    segments.length === 0 ||
    segments.some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    throw new PragmaBundleFormatError("archive.path_unsafe", `Unsafe bundle path: ${path}`);
  }
  return `${segments.join("/")}${isDirectory ? "/" : ""}`;
}

function portableCollisionKey(path: string): string {
  return path.normalize("NFC").toLocaleLowerCase("en-US");
}

async function zipArchive(files: ReadonlyMap<string, Uint8Array>): Promise<Uint8Array> {
  return await new Promise((resolvePromise, reject) => {
    zip(Object.fromEntries(files), { level: 6 }, (error, result) => {
      if (error !== null) reject(error);
      else resolvePromise(result);
    });
  });
}

async function unzipArchive(
  raw: Uint8Array,
  options: AsyncUnzipOptions,
): Promise<Record<string, Uint8Array>> {
  return await new Promise((resolvePromise, reject) => {
    unzip(raw, options, (error, result) => {
      if (error !== null) reject(error);
      else resolvePromise(result);
    });
  });
}
