import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dslRoot = join(root, "dsl");
const output = join(root, "src", "builtin.generated.ts");

async function filesAt(path) {
  const entries = await readdir(path, { withFileTypes: true });
  const files = [];
  for (const entry of entries.toSorted((left, right) => left.name.localeCompare(right.name))) {
    const target = join(path, entry.name);
    if (entry.isDirectory()) files.push(...(await filesAt(target)));
    else files.push(target);
  }
  return files;
}

const files = await filesAt(dslRoot);
const records = await Promise.all(
  files.map(async (path) => [
    relative(dslRoot, path).replaceAll("\\", "/"),
    await readFile(path, "utf8"),
  ]),
);
const source = [
  "// Generated by scripts/generate-builtin.mjs. Do not edit directly.",
  "// prettier-ignore",
  "export const BUILT_IN_STEWARD_FILES: Readonly<Record<string, string>> = " +
    JSON.stringify(Object.fromEntries(records), null, 2) +
    " as const;",
  "",
].join("\n");
await writeFile(output, source);
